apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    compileSdk 34




    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    publishing {
        publishing {
            singleVariant("release") {
                withSourcesJar()
                withJavadocJar()
            }
        }
    }
    namespace 'com.barikoi.barikoitrace'

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'androidx.work:work-runtime:2.7.1'
    implementation 'androidx.concurrent:concurrent-futures:1.2.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.google.android.gms:play-services-location:21.3.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation ('io.socket:socket.io-client:2.1.1') {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }
    implementation "com.github.hannesa2:paho.mqtt.android:4.4"
//    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
//    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

}

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.github.barikoi'
            artifactId = 'barikoitrace'
            version = '0.3.0'

            afterEvaluate {
                from components.release
            }
        }
    }
}
