apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.barikoi.barikoitracesdkapp"
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Default API key (can be overridden by flavors)
        buildConfigField "String", "API_KEY", "\"MjA1NDo4MjBSTUxLTEs5\""
    }

    flavorDimensions += "brand"
    productFlavors {
        jti {
            applicationIdSuffix ".jti"
            versionNameSuffix "-jti"
            buildConfigField "String", "API_KEY", "\"bkoi_0ec844c9848b08912985e584268178b323239a6a32a0da9fa139cc9515aecd22\""
            dimension "brand"
        }

        akg {
            applicationIdSuffix ".akg"
            versionNameSuffix "-akg"
            buildConfigField "String", "API_KEY", "\"bkoi_93a10397ab1c13934fc6d719b3e09d6bdcb23894ea4ab1f4e7ec8d2a96dcfb41\""
            dimension "brand"
        }

        barikoi {
            // Default/Barikoi flavor - no suffixes
            buildConfigField "String", "API_KEY", "\"MjA1NDo4MjBSTUxLTEs5\""
            dimension "brand"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    namespace 'com.barikoi.barikoitracesdkapp'
}

dependencies {
    implementation project(':barikoiloctrace')
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.core:core-ktx:1.15.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'com.google.android.material:material:1.2.0-alpha01'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.4'
}
